/* Main.c file generated by New Project wizard
 *
 * Created:   2020
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#define _XTAL_FREQ 8000000  

#include <string.h>
#include "config.h"
#include "GLCD.h"
#include "splash.h"

#define PANTALLA 0 
#define INNIT 1
#define RUNNING 2
#define STOPPED 3
#define ENDGAME 4

int dino[2][13] = {0xE0, 0xC0, 0x80, 0x80, 0xC0, 0xE0, 0xFE, 0xFF, 0xFD, 0x5F, 0xD7, 0x07, 0x06, 
                   0x01, 0x03, 0x07, 0x7F, 0x5F, 0x0F, 0x7F, 0x47, 0x03, 0x00, 0x00, 0x00, 0x00};
int estat = PANTALLA;
char nom[11] = "Peilin Ni\n";
int first = 1;
char s1[] = "Points:   0  Lives:\n";

void dibuixarCors(){
    putchGLCD(0,19,'-');
    putchGLCD(0,21,'-');
    putchGLCD(0,23,'-');
    
}

void pintarDino(int k, int kf, int l, int lf){
   //PRE: passem el numero per imprimir i les coordenades k(pagina inicial) kf(pagina final)
   // l(pixel de la columna d'inici) lf(pixel de la columna final),
   //POST: imprimeix el numero a les coordenades  que li hem passat
   int x = 0;
   for(int i = k; i < kf; ++i){
      int y = 0;
      for(int j = l; j < lf; ++j){
	 writeByte(i,j,dino[x][y]);
	 ++y;
      }
      ++x;
   }
}

void pantallaInici(){
   int pos = 0, aux, x = 0, y = 0; 
   for(int i = 0; i < 8; ++i){
      for(int j = 0; j < 128; ++j){
	 aux = bitmap[pos];
	 writeByte(x,y,aux);
	 ++y;
	 ++pos;
      }
      y = 0;
      ++x;
   }
   __delay_ms(3000);
   clearGLCD(0,7,0,127);
}

void writeTxt(byte page, byte y, char * s) {
	int i=0;
	while (*s!='\n' && *s!='\0') {
		putchGLCD(page, y+i, *(s++));
		i++;
	};
}

void configPic(){
   ANSELA = 0x01; 
   ANSELB = 0;             //PORTB configurat com Digital
   ANSELD = 0;             //PORTD configurat com Digital 
   PORTA = 0;   
   PORTB = 0; 		   //Donem uns valors inicials als ports
   PORTD = 0;
   TRISA = 0x07; //configurem RA0, RA1, RA2 d'entrada   
   TRISB = 0x00;		   //Configurem B i D de sortida
   TRISD = 0x00;
}

void configRecepcio(){
 
}

void configEnviar(){
   SPBRGH1 = 0; 
   SPBRG1 = 16;
   
   BAUDCONbits.BRG16 = 1; 
   TXSTA1bits.BRGH =1;
   TXSTA1bits.SYNC = 0; 
   TXSTA1bits.TX9 = 0;
   TXSTA1bits.TXEN = 1; 
   
   RCSTA1bits.SPEN = 1; 
}

void sendChar(char c){
   TXREG1 = c;
   while(TX1IF == 0); 
}

void sendName(void){
   for(int i = 0; i< 20; ++i){
      char c = nom[i];
      sendChar(c);
   }
}

void main(void){
   configPic(); 
   configRecepcio(); 
   configEnviar();
   
   GLCDinit();		   //Inicialitzem la pantalla
   clearGLCD(0,7,0,127);      //Esborrem pantalla
   setStartLine(0);   //Definim linia d'inici 

   sendName();
   while (1){
      if(estat == PANTALLA){
	 pantallaInici();
	 estat = INNIT;
      }
      else if(estat == INNIT){
	 if(first == 1) {
	    writeTxt(0,0,s1);
	    dibuixarCors();
	    pintarDino(6,8,0,13);
	    first = 0; 
	 }
      }
   }
}
